"""Model card for the first-order proton NMR slice."""

from __future__ import annotations

from chemworld.physchem.maturity import MaturityLevel, ModelCard, ValidationEvidence


def proton_nmr_model_cards() -> tuple[ModelCard, ...]:
    return (
        ModelCard(
            model_id="first_order_proton_nmr_assignments_v1",
            module_id="spectroscopy_instruments",
            title="First-Order Proton NMR Assignments And Integrals",
            maturity=MaturityLevel.REFERENCE_VALIDATED,
            summary=(
                "Provenance-tagged proton shift anchors with first-order "
                "multiplicity/J splitting, amount-weighted integration, solvent "
                "reference correction, and explicit interference diagnostics."
            ),
            equations=(
                "delta_corrected = delta_anchor + delta_ref,expected - delta_ref,observed",
                "line offset (ppm) = coupling offset (Hz) / spectrometer frequency (MHz)",
                "doublet/triplet/quartet/quintet intensities follow Pascal rows",
                "raw integral = species amount * proton count * response factor",
                "normalized integral = raw integral / sum(raw integrals)",
                "second-order risk when Delta nu / max(J) < 10",
            ),
            assumptions=(
                "Chemical shifts, assignments, proton counts, line widths, and "
                "couplings are curated anchors with provenance.",
                "Splitting is first order; dd is generated by sequential "
                "doublet splitting and generic multiplets remain unresolved.",
                "Integrals are quantitative only to the declared response factors.",
                "Solvent interference uses declared residual peaks and a ppm tolerance.",
            ),
            validity_limits=(
                "Supported multiplicities are s, br_s, d, t, q, quint, dd, and m.",
                "Second-order, strong-coupling, exchange, relaxation, and "
                "concentration effects are warnings rather than solved spin dynamics.",
                "The implementation covers 1H stick-line metadata, not 2D NMR "
                "or full lineshape simulation.",
            ),
            failure_modes=(
                "Multiplicity/coupling-count mismatches and invalid signal "
                "parameters fail during spec construction.",
                "Missing species amounts and duplicate signal ids fail before synthesis.",
                "Solvent overlap, signal overlap, second-order risk, exchangeable "
                "protons, and unresolved multiplets are machine-readable warnings.",
            ),
            units={
                "chemical shift/reference tolerance": "ppm",
                "coupling/line width": "Hz",
                "spectrometer frequency": "MHz",
                "species amount": "mol",
                "integral/intensity/proton count": "relative; relative; count",
            },
            reference_reading=(
                "First-order spin-spin splitting and Pascal-triangle intensity "
                "conventions for introductory 1H NMR",
                "IUPAC chemical-shift referencing and residual-solvent peak reporting conventions",
                "Delta-nu/J strong-coupling screening criterion and quantitative "
                "NMR integral proportionality conventions",
            ),
            validation_evidence=(
                ValidationEvidence(
                    evidence_id="nmr-first-order-splitting-and-reference",
                    evidence_type="analytical_test",
                    description=(
                        "Checks triplet line positions/intensities, Hz-to-ppm "
                        "conversion, reference correction, and solvent overlap."
                    ),
                    status="implemented",
                    command_or_path="tests/test_nmr.py",
                    tolerance="pytest.approx analytical positions/intensities",
                ),
                ValidationEvidence(
                    evidence_id="nmr-integral-and-failure-diagnostics",
                    evidence_type="unit_test",
                    description=(
                        "Checks amount/proton integration ratios, overlap, "
                        "second-order, exchangeable/multiplet warnings, and "
                        "multiplicity validation."
                    ),
                    status="implemented",
                    command_or_path="tests/test_nmr.py",
                    tolerance="exact warnings and pytest.approx integrals",
                ),
            ),
            model_limit_notes=(
                "Reference validation describes a structured NMR evidence "
                "layer, not quantum-chemical shift prediction or spin simulation.",
                "NOE, relaxation, phase/baseline correction, shimming, dynamic "
                "exchange, decoupling, and 2D correlations remain outside scope.",
            ),
            intended_use=(
                "Assignment, identity, purity, and mixture-ratio benchmark tasks.",
                "Agent interpretation of shift, multiplicity, coupling, integral, "
                "solvent, overlap, and model-limit metadata.",
            ),
        ),
    )


__all__ = ["proton_nmr_model_cards"]
