"""Reaction ODE kernel for the shared ChemWorld law."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
from scipy.integrate import solve_ivp

from chemworld.foundation import Reaction, WorldState

R_GAS = 8.31446261815324
REACTION_SPECIES = ("A", "P", "B", "D", "E", "Cat_active", "Cat_dead")


@dataclass(frozen=True)
class ReactionIntegrationResult:
    species_amounts: dict[str, float]
    temperature_K: float
    duration_s: float
    cost_delta: float
    energy_jacket_J: float
    heat_reaction_J: float
    heat_loss_J: float
    stirring_speed_rpm: float


def reaction_network() -> tuple[Reaction, ...]:
    return (
        Reaction("r1", "A -> P", {"A": -1.0, "P": 1.0}, -42_000.0),
        Reaction("r2", "A -> B", {"A": -1.0, "B": 1.0}, -25_000.0),
        Reaction("r3", "P -> D", {"P": -1.0, "D": 1.0}, -18_000.0),
        Reaction("r4", "A + P -> E", {"A": -1.0, "P": -1.0, "E": 1.0}, -35_000.0),
        Reaction(
            "r5",
            "Cat_active -> Cat_dead",
            {"Cat_active": -1.0, "Cat_dead": 1.0},
            -5_000.0,
        ),
    )


def integrate_reaction_ode(
    *,
    state: WorldState,
    world: Any,
    duration_s: float,
    target_temperature_K: float,
    heat: bool,
    stirring_speed_rpm: float,
) -> ReactionIntegrationResult | None:
    """Integrate reaction and simplified thermal ODEs.

    The world object is deliberately structural: it must expose the hidden
    parameter arrays generated by the scenario layer, but this module does not
    import the concrete core parameter class.
    """

    duration = float(np.clip(duration_s, 0.0, 14_400.0))
    if duration <= 0.0 or state.volume_L <= 0.0:
        return None

    target_temperature = float(np.clip(target_temperature_K, 250.0, 520.0))
    stirring_speed = float(np.clip(stirring_speed_rpm, 100.0, 1200.0))
    y0 = np.array(
        [state.species_amounts[key] for key in REACTION_SPECIES]
        + [state.temperature_K, 0.0, 0.0, 0.0],
    )
    result = solve_ivp(
        lambda _t, y: reaction_ode_rhs(
            y=y,
            state=state,
            world=world,
            target_temperature_K=target_temperature,
            heat=heat,
            stirring_speed_rpm=stirring_speed,
        ),
        (0.0, duration),
        y0,
        method="RK45",
        rtol=1.0e-6,
        atol=1.0e-10,
    )
    y = np.maximum(result.y[:, -1], 0.0)
    return ReactionIntegrationResult(
        species_amounts={key: float(y[index]) for index, key in enumerate(REACTION_SPECIES)},
        temperature_K=float(np.clip(y[7], 250.0, 520.0)),
        duration_s=duration,
        cost_delta=duration / 3600.0 * (0.03 if heat else 0.01),
        energy_jacket_J=float(y[8]),
        heat_reaction_J=float(y[9]),
        heat_loss_J=float(y[10]),
        stirring_speed_rpm=stirring_speed,
    )


def reaction_ode_rhs(
    *,
    y: np.ndarray,
    state: WorldState,
    world: Any,
    target_temperature_K: float,
    heat: bool,
    stirring_speed_rpm: float,
) -> np.ndarray:
    amounts = np.maximum(y[:7], 0.0)
    temperature = float(np.clip(y[7], 250.0, 520.0))
    volume = max(state.volume_L, 1.0e-6)
    catalyst = int(state.metadata.get("catalyst", 0))
    solvent = int(state.metadata.get("solvent", 0))
    concentrations = amounts / volume
    cat_total = max(amounts[5] + amounts[6], 1.0e-12)
    eta_cat = amounts[5] / cat_total

    k = world.pre_exponential * np.exp(-world.activation_energy / (R_GAS * temperature))
    k *= world.catalyst_effects[catalyst] * world.solvent_effects[solvent]
    stir_factor = 0.70 + 0.30 * (1.0 - np.exp(-stirring_speed_rpm / 420.0))
    low_mixing_side_penalty = 1.0 + 0.15 * (
        1.0 / (1.0 + np.exp((stirring_speed_rpm - 360.0) / 90.0))
    )
    rates = np.array(
        [
            k[0] * concentrations[0] * eta_cat * volume * stir_factor,
            k[1] * concentrations[0] * volume * low_mixing_side_penalty,
            k[2] * concentrations[1] * volume,
            k[3] * concentrations[0] * concentrations[1] * volume * low_mixing_side_penalty,
            k[4] * amounts[5],
        ],
    )
    derivatives = np.zeros(11)
    derivatives[0] = -rates[0] - rates[1] - rates[3]
    derivatives[1] = rates[0] - rates[2] - rates[3]
    derivatives[2] = rates[1]
    derivatives[3] = rates[2]
    derivatives[4] = rates[3]
    derivatives[5] = -rates[4]
    derivatives[6] = rates[4]

    q_jacket = 0.0
    if heat:
        q_jacket = float(np.clip((target_temperature_K - temperature) * 4.0, -70.0, 90.0))
    heat_loss = world.ua_W_per_K * (temperature - world.environment_temperature_K)
    heat_reaction = float(np.dot(world.delta_h_J_per_mol, rates))
    heat_capacity = max(world.rho_cp_J_per_L_K * volume, 1.0e-6)
    derivatives[7] = (q_jacket - heat_loss - heat_reaction) / heat_capacity
    derivatives[8] = q_jacket
    derivatives[9] = heat_reaction
    derivatives[10] = heat_loss
    return derivatives


@dataclass(frozen=True)
class ReactionModuleSpec:
    module_id: str = "reaction"
    version: str = "0.3"
    laws: tuple[str, ...] = (
        "arrhenius_kinetics",
        "catalyst_solvent_effects",
        "byproduct_formation",
        "product_degradation",
        "catalyst_deactivation",
    )

    def to_dict(self) -> dict[str, object]:
        return {
            "module_id": self.module_id,
            "version": self.version,
            "laws": list(self.laws),
            "gas_constant_J_per_mol_K": R_GAS,
            "reactions": [reaction.to_dict() for reaction in reaction_network()],
        }


__all__ = [
    "REACTION_SPECIES",
    "R_GAS",
    "ReactionIntegrationResult",
    "ReactionModuleSpec",
    "integrate_reaction_ode",
    "reaction_network",
    "reaction_ode_rhs",
]
