"""Reaction ODE kernel for the shared ChemWorld law."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

import numpy as np
from scipy.integrate import solve_ivp

from chemworld.foundation import Reaction, WorldState, equipment_settings

R_GAS = 8.31446261815324
REACTION_SPECIES = ("A", "P", "B", "D", "E", "Cat_active", "Cat_dead")


@dataclass(frozen=True)
class ReactionIntegrationResult:
    species_amounts: dict[str, float]
    temperature_K: float
    duration_s: float
    cost_delta: float
    energy_jacket_J: float
    heat_reaction_J: float
    heat_loss_J: float
    stirring_speed_rpm: float


def reaction_network() -> tuple[Reaction, ...]:
    return (
        Reaction("r1", "A -> P", {"A": -1.0, "P": 1.0}, -42_000.0),
        Reaction("r2", "A -> B", {"A": -1.0, "B": 1.0}, -25_000.0),
        Reaction("r3", "P -> D", {"P": -1.0, "D": 1.0}, -18_000.0),
        Reaction("r4", "A + P -> E", {"A": -1.0, "P": -1.0, "E": 1.0}, -35_000.0),
        Reaction(
            "r5",
            "Cat_active -> Cat_dead",
            {"Cat_active": -1.0, "Cat_dead": 1.0},
            -5_000.0,
        ),
    )


def integrate_reaction_ode(
    *,
    state: WorldState,
    world: Any,
    duration_s: float,
    target_temperature_K: float,
    heat: bool,
    stirring_speed_rpm: float,
    species_map: Mapping[str, str] | None = None,
) -> ReactionIntegrationResult | None:
    """Integrate reaction and simplified thermal ODEs.

    The world object is deliberately structural: it must expose the hidden
    parameter arrays generated by the scenario layer, but this module does not
    import the concrete core parameter class.
    """

    duration = float(np.clip(duration_s, 0.0, 14_400.0))
    if duration <= 0.0 or state.volume_L <= 0.0:
        return None

    target_temperature = float(np.clip(target_temperature_K, 250.0, 520.0))
    stirring_speed = float(np.clip(stirring_speed_rpm, 100.0, 1200.0))
    resolved_species_map = {
        species_id: (species_map or {}).get(species_id, species_id)
        for species_id in REACTION_SPECIES
    }
    y0 = np.array(
        [
            state.species_amounts.get(resolved_species_map[key], 0.0)
            for key in REACTION_SPECIES
        ]
        + [state.temperature_K, 0.0, 0.0, 0.0],
    )
    result = solve_ivp(
        lambda _t, y: reaction_ode_rhs(
            y=y,
            state=state,
            world=world,
            target_temperature_K=target_temperature,
            heat=heat,
            stirring_speed_rpm=stirring_speed,
        ),
        (0.0, duration),
        y0,
        method="RK45",
        rtol=1.0e-6,
        atol=1.0e-10,
    )
    y = np.maximum(result.y[:, -1], 0.0)
    species_amounts = state.species_amounts.copy()
    for index, canonical_species in enumerate(REACTION_SPECIES):
        mechanism_species = resolved_species_map[canonical_species]
        species_amounts[mechanism_species] = float(y[index])
    return ReactionIntegrationResult(
        species_amounts=species_amounts,
        temperature_K=float(np.clip(y[7], 250.0, 520.0)),
        duration_s=duration,
        cost_delta=duration / 3600.0 * (0.03 if heat else 0.01),
        energy_jacket_J=float(y[8]),
        heat_reaction_J=float(y[9]),
        heat_loss_J=float(y[10]),
        stirring_speed_rpm=stirring_speed,
    )


def integrate_compiled_reaction_ode(
    *,
    state: WorldState,
    world: Any,
    compiled_mechanism: Any,
    duration_s: float,
    target_temperature_K: float,
    heat: bool,
    stirring_speed_rpm: float,
) -> ReactionIntegrationResult | None:
    """Integrate a mechanism-compiled reaction network and thermal balance.

    Runtime v2 treats mechanism YAML as the owner of species and reactions. The
    legacy seven-slot ODE remains available only as an explicit reference
    fixture through ``integrate_reaction_ode``.
    """

    if compiled_mechanism is None:
        raise ValueError("compiled_mechanism is required for Runtime v2 reaction integration")

    duration = float(np.clip(duration_s, 0.0, 14_400.0))
    if duration <= 0.0 or state.volume_L <= 0.0:
        return None

    network = compiled_mechanism.network
    species_ids = network.species_ids
    target_temperature = float(np.clip(target_temperature_K, 250.0, 520.0))
    stirring_speed = float(np.clip(stirring_speed_rpm, 100.0, 1200.0))
    y0 = np.array(
        [state.species_amounts.get(species_id, 0.0) for species_id in species_ids]
        + [state.temperature_K, 0.0, 0.0, 0.0],
    )
    result = solve_ivp(
        lambda _t, y: compiled_reaction_ode_rhs(
            y=y,
            state=state,
            world=world,
            compiled_mechanism=compiled_mechanism,
            target_temperature_K=target_temperature,
            heat=heat,
            stirring_speed_rpm=stirring_speed,
        ),
        (0.0, duration),
        y0,
        method="LSODA",
        rtol=1.0e-7,
        atol=1.0e-11,
    )
    if not result.success:
        raise RuntimeError(f"Compiled mechanism integration failed: {result.message}")
    y = np.maximum(result.y[:, -1], 0.0)
    species_amounts = state.species_amounts.copy()
    for index, species_id in enumerate(species_ids):
        species_amounts[species_id] = float(y[index])
    offset = len(species_ids)
    return ReactionIntegrationResult(
        species_amounts=species_amounts,
        temperature_K=float(np.clip(y[offset], 250.0, 520.0)),
        duration_s=duration,
        cost_delta=duration / 3600.0 * (0.03 if heat else 0.01),
        energy_jacket_J=float(y[offset + 1]),
        heat_reaction_J=float(y[offset + 2]),
        heat_loss_J=float(y[offset + 3]),
        stirring_speed_rpm=stirring_speed,
    )


def compiled_reaction_ode_rhs(
    *,
    y: np.ndarray,
    state: WorldState,
    world: Any,
    compiled_mechanism: Any,
    target_temperature_K: float,
    heat: bool,
    stirring_speed_rpm: float,
) -> np.ndarray:
    network = compiled_mechanism.network
    species_ids = network.species_ids
    species_count = len(species_ids)
    amounts_array = np.maximum(y[:species_count], 0.0)
    temperature = float(np.clip(y[species_count], 250.0, 520.0))
    volume = max(state.volume_L, 1.0e-6)
    amounts = {
        species_id: float(amount)
        for species_id, amount in zip(species_ids, amounts_array, strict=True)
    }
    rates_mol_L_s = network.reaction_rates(
        amounts,
        volume_L=volume,
        temperature_K=temperature,
    )
    reactor_settings = equipment_settings(state.equipment, "batch_reactor")
    catalyst = int(reactor_settings.get("catalyst", 0))
    solvent = int(reactor_settings.get("solvent", 0))
    stirring_factor = 0.70 + 0.30 * (1.0 - np.exp(-stirring_speed_rpm / 420.0))

    derivatives = np.zeros(species_count + 4)
    reaction_heat_W = 0.0
    for reaction_index, reaction in enumerate(network.reactions):
        hidden_modifier = _hidden_reaction_modifier(
            world,
            catalyst=catalyst,
            solvent=solvent,
            reaction_index=reaction_index,
            stirring_factor=stirring_factor,
        )
        rate_mol_s = rates_mol_L_s[reaction.reaction_id] * volume * hidden_modifier
        for species_id, coefficient in reaction.stoichiometry.items():
            derivatives[network.species_index[species_id]] += coefficient * rate_mol_s
        reaction_heat_W += reaction.delta_h_J_per_mol * rate_mol_s

    q_jacket = 0.0
    if heat:
        q_jacket = float(np.clip((target_temperature_K - temperature) * 4.0, -70.0, 90.0))
    heat_loss = world.ua_W_per_K * (temperature - world.environment_temperature_K)
    heat_capacity = max(world.rho_cp_J_per_L_K * volume, 1.0e-6)
    derivatives[species_count] = (q_jacket - heat_loss - reaction_heat_W) / heat_capacity
    derivatives[species_count + 1] = q_jacket
    derivatives[species_count + 2] = reaction_heat_W
    derivatives[species_count + 3] = heat_loss
    return derivatives


def _hidden_reaction_modifier(
    world: Any,
    *,
    catalyst: int,
    solvent: int,
    reaction_index: int,
    stirring_factor: float,
) -> float:
    catalyst_effects = np.asarray(world.catalyst_effects, dtype=float)
    solvent_effects = np.asarray(world.solvent_effects, dtype=float)
    catalyst_index = int(np.clip(catalyst, 0, catalyst_effects.shape[0] - 1))
    solvent_index = int(np.clip(solvent, 0, solvent_effects.shape[0] - 1))
    catalyst_reaction_index = min(reaction_index, catalyst_effects.shape[-1] - 1)
    solvent_reaction_index = min(reaction_index, solvent_effects.shape[-1] - 1)
    catalyst_factor = (
        catalyst_effects[catalyst_index, catalyst_reaction_index]
        if catalyst_effects.ndim == 2
        else catalyst_effects[catalyst_index]
    )
    solvent_factor = (
        solvent_effects[solvent_index, solvent_reaction_index]
        if solvent_effects.ndim == 2
        else solvent_effects[solvent_index]
    )
    return float(catalyst_factor * solvent_factor * stirring_factor)


def reaction_ode_rhs(
    *,
    y: np.ndarray,
    state: WorldState,
    world: Any,
    target_temperature_K: float,
    heat: bool,
    stirring_speed_rpm: float,
) -> np.ndarray:
    amounts = np.maximum(y[:7], 0.0)
    temperature = float(np.clip(y[7], 250.0, 520.0))
    volume = max(state.volume_L, 1.0e-6)
    reactor_settings = equipment_settings(state.equipment, "batch_reactor")
    catalyst = int(reactor_settings.get("catalyst", 0))
    solvent = int(reactor_settings.get("solvent", 0))
    concentrations = amounts / volume
    cat_total = max(amounts[5] + amounts[6], 1.0e-12)
    eta_cat = amounts[5] / cat_total

    k = world.pre_exponential * np.exp(-world.activation_energy / (R_GAS * temperature))
    k *= world.catalyst_effects[catalyst] * world.solvent_effects[solvent]
    stir_factor = 0.70 + 0.30 * (1.0 - np.exp(-stirring_speed_rpm / 420.0))
    low_mixing_side_penalty = 1.0 + 0.15 * (
        1.0 / (1.0 + np.exp((stirring_speed_rpm - 360.0) / 90.0))
    )
    rates = np.array(
        [
            k[0] * concentrations[0] * eta_cat * volume * stir_factor,
            k[1] * concentrations[0] * volume * low_mixing_side_penalty,
            k[2] * concentrations[1] * volume,
            k[3] * concentrations[0] * concentrations[1] * volume * low_mixing_side_penalty,
            k[4] * amounts[5],
        ],
    )
    derivatives = np.zeros(11)
    derivatives[0] = -rates[0] - rates[1] - rates[3]
    derivatives[1] = rates[0] - rates[2] - rates[3]
    derivatives[2] = rates[1]
    derivatives[3] = rates[2]
    derivatives[4] = rates[3]
    derivatives[5] = -rates[4]
    derivatives[6] = rates[4]

    q_jacket = 0.0
    if heat:
        q_jacket = float(np.clip((target_temperature_K - temperature) * 4.0, -70.0, 90.0))
    heat_loss = world.ua_W_per_K * (temperature - world.environment_temperature_K)
    heat_reaction = float(np.dot(world.delta_h_J_per_mol, rates))
    heat_capacity = max(world.rho_cp_J_per_L_K * volume, 1.0e-6)
    derivatives[7] = (q_jacket - heat_loss - heat_reaction) / heat_capacity
    derivatives[8] = q_jacket
    derivatives[9] = heat_reaction
    derivatives[10] = heat_loss
    return derivatives


@dataclass(frozen=True)
class ReactionModuleSpec:
    module_id: str = "reaction"
    version: str = "0.3"
    laws: tuple[str, ...] = (
        "arrhenius_kinetics",
        "catalyst_solvent_effects",
        "byproduct_formation",
        "product_degradation",
        "catalyst_deactivation",
    )

    def to_dict(self) -> dict[str, object]:
        return {
            "module_id": self.module_id,
            "version": self.version,
            "laws": list(self.laws),
            "gas_constant_J_per_mol_K": R_GAS,
            "reactions": [reaction.to_dict() for reaction in reaction_network()],
        }


__all__ = [
    "REACTION_SPECIES",
    "R_GAS",
    "ReactionIntegrationResult",
    "ReactionModuleSpec",
    "compiled_reaction_ode_rhs",
    "integrate_compiled_reaction_ode",
    "integrate_reaction_ode",
    "reaction_network",
    "reaction_ode_rhs",
]
