"""Default species-role bindings for ChemWorld mechanism cards."""

from __future__ import annotations

LEGACY_REACTANT_SPECIES = "A"
LEGACY_TARGET_SPECIES = "P"
LEGACY_IMPURITY_SPECIES = ("B", "D", "E")
LEGACY_ACTIVE_CATALYST_SPECIES = "Cat_active"
LEGACY_BYPRODUCT_SPECIES = ("B", "E")
LEGACY_DEGRADATION_SPECIES = ("D",)
LEGACY_INITIAL_REACTANT_METADATA_KEY = f"initial_{LEGACY_REACTANT_SPECIES}_mol"
PHASE_PRODUCT_AMOUNT_KEY = "product_mol"
LEGACY_PHASE_PRODUCT_AMOUNT_KEY = f"{LEGACY_TARGET_SPECIES}_mol"


__all__ = [
    "LEGACY_ACTIVE_CATALYST_SPECIES",
    "LEGACY_BYPRODUCT_SPECIES",
    "LEGACY_DEGRADATION_SPECIES",
    "LEGACY_IMPURITY_SPECIES",
    "LEGACY_INITIAL_REACTANT_METADATA_KEY",
    "LEGACY_PHASE_PRODUCT_AMOUNT_KEY",
    "LEGACY_REACTANT_SPECIES",
    "LEGACY_TARGET_SPECIES",
    "PHASE_PRODUCT_AMOUNT_KEY",
]
